# Generated by Django 5.1.14 on 2026-05-04 20:48

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="Alternative names for fuzzy search and deduplication.",
                        size=None,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=255)),
                (
                    "overall_safety_score",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="0–100. Updated automatically by AI agents.",
                        null=True,
                    ),
                ),
                (
                    "health_index",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="nutrii Health Index (NHI). 0–100. Updated by AI agents.",
                        null=True,
                    ),
                ),
                ("ban_listed", models.BooleanField(default=False)),
                ("image_url", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ai_guide_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Current active version of the agent instruction guide.",
                        null=True,
                    ),
                ),
                (
                    "last_analyzed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the AI last reviewed this food.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Molecule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pubchem_cid",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("iupac_name", models.CharField(blank=True, max_length=500)),
                ("cas_number", models.CharField(blank=True, max_length=50)),
                ("molecular_formula", models.CharField(blank=True, max_length=100)),
                (
                    "molecular_weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "harm_level",
                    models.SmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Negligible"),
                            (2, "Low"),
                            (3, "Moderate"),
                            (4, "High"),
                            (5, "Critical"),
                        ],
                        default=0,
                        help_text="0–5. Auto-adjusted by AI from new studies.",
                    ),
                ),
                (
                    "harm_mechanisms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="Plain-language harm mechanism tags.",
                        size=None,
                    ),
                ),
                (
                    "threshold_concern_mg_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("is_heat_stable", models.BooleanField(default=True)),
                ("is_neutralizable", models.BooleanField(default=False)),
                ("structure_image_url", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("mechanism", models.TextField(blank=True)),
                (
                    "typical_temperature_c",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "typical_duration_min",
                    models.SmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pmid", models.CharField(max_length=20, unique=True)),
                ("title", models.TextField()),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("journal", models.CharField(blank=True, max_length=255)),
                ("publication_year", models.SmallIntegerField(blank=True, null=True)),
                ("url", models.TextField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "ai_safety_impact",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="−5 to +5. AI-assessed impact on safety perception.",
                        null=True,
                    ),
                ),
                (
                    "ai_health_impact",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="−5 to +5. AI-assessed impact on health perception.",
                        null=True,
                    ),
                ),
                (
                    "ai_confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ai_model_used", models.CharField(blank=True, max_length=100)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "studies",
                "ordering": ["-publication_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="BanListEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "lethal_dose_mg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("is_conditionally_safe", models.BooleanField(default=False)),
                (
                    "safe_condition",
                    models.TextField(
                        blank=True,
                        help_text="Condition under which this food may be consumed safely.",
                    ),
                ),
                (
                    "regulatory_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-jurisdiction regulatory status as JSONB.",
                    ),
                ),
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban_entry",
                        to="core.food",
                    ),
                ),
            ],
            options={
                "verbose_name": "ban list entry",
                "verbose_name_plural": "ban list entries",
            },
        ),
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.foodcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "food categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foods",
                to="core.foodcategory",
            ),
        ),
        migrations.CreateModel(
            name="IngredientAIGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guide_markdown", models.TextField()),
                ("version", models.IntegerField(default=1)),
                (
                    "generated_by",
                    models.CharField(
                        blank=True, help_text="OpenRouter model name.", max_length=100
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_guides",
                        to="core.food",
                    ),
                ),
                (
                    "molecule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_guides",
                        to="core.molecule",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingredient AI guide",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="FoodMolecule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_per_100g",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="mg, µg, g, IU, etc.", max_length=20
                    ),
                ),
                (
                    "amount_notes",
                    models.TextField(blank=True, help_text='e.g. "varies by cultivar"'),
                ),
                (
                    "is_beneficial",
                    models.BooleanField(
                        default=False,
                        help_text="Context-dependent: is this molecule a net benefit for this food?",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.food"
                    ),
                ),
                (
                    "molecule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.molecule"
                    ),
                ),
            ],
            options={
                "verbose_name": "food–molecule link",
                "unique_together": {("food", "molecule")},
            },
        ),
        migrations.AddField(
            model_name="food",
            name="molecules",
            field=models.ManyToManyField(
                blank=True,
                related_name="foods",
                through="core.FoodMolecule",
                to="core.molecule",
            ),
        ),
        migrations.CreateModel(
            name="MoleculeNeutralization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reduction_percent_min",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Minimum reduction percentage (0–100).",
                        null=True,
                    ),
                ),
                (
                    "reduction_percent_max",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Maximum reduction percentage (0–100).",
                        null=True,
                    ),
                ),
                (
                    "time_required",
                    models.CharField(
                        blank=True,
                        help_text='Human-readable time, e.g. "10–30 minutes".',
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text='e.g. "Discard soaking water after use."'
                    ),
                ),
                (
                    "evidence_refs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text="PubMed PMIDs supporting this claim.",
                        size=None,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "molecule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.molecule"
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.processingmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "molecule neutralization",
            },
        ),
        migrations.AddField(
            model_name="molecule",
            name="neutralization_methods",
            field=models.ManyToManyField(
                blank=True,
                related_name="molecules",
                through="core.MoleculeNeutralization",
                to="core.processingmethod",
            ),
        ),
        migrations.CreateModel(
            name="SafetyScoreRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_safety_score", models.SmallIntegerField(blank=True, null=True)),
                ("new_safety_score", models.SmallIntegerField(blank=True, null=True)),
                ("old_health_index", models.SmallIntegerField(blank=True, null=True)),
                ("new_health_index", models.SmallIntegerField(blank=True, null=True)),
                (
                    "reason",
                    models.TextField(
                        help_text="AI-generated explanation for the change."
                    ),
                ),
                ("ai_model_used", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_revisions",
                        to="core.food",
                    ),
                ),
                (
                    "triggering_study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_revisions",
                        to="core.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "safety score revision",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0.00–1.00. How relevant is this study to this food?",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "linked_by",
                    models.CharField(
                        choices=[
                            ("auto_ingestion", "Auto Ingestion"),
                            ("ai_cross_reference", "AI Cross-Reference"),
                        ],
                        default="auto_ingestion",
                        max_length=50,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.food"
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.study"
                    ),
                ),
            ],
            options={
                "verbose_name": "food–study link",
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="idx_food_name"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["ban_listed"], name="idx_food_ban_listed"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["health_index"], name="idx_food_health_index"),
        ),
        migrations.AlterUniqueTogether(
            name="moleculeneutralization",
            unique_together={("molecule", "method")},
        ),
        migrations.AddIndex(
            model_name="molecule",
            index=models.Index(fields=["pubchem_cid"], name="idx_molecule_pubchem_cid"),
        ),
        migrations.AddIndex(
            model_name="molecule",
            index=models.Index(fields=["cas_number"], name="idx_molecule_cas"),
        ),
        migrations.AddIndex(
            model_name="molecule",
            index=models.Index(fields=["harm_level"], name="idx_molecule_harm_level"),
        ),
        migrations.AlterUniqueTogether(
            name="foodstudy",
            unique_together={("food", "study")},
        ),
    ]
