# Generated by Django 5.1.15 on 2026-06-10 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postgres_trigram_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='health_index',
            field=models.SmallIntegerField(blank=True, help_text='nutrii Health Index (NHI). 0–100. Updated by AI agents.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='overall_safety_score',
            field=models.SmallIntegerField(blank=True, help_text='0–100. Updated automatically by AI agents.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='harm_level',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Negligible'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Critical')], default=0, help_text='0–5. Auto-adjusted by AI from new studies.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='moleculeneutralization',
            name='reduction_percent_max',
            field=models.SmallIntegerField(blank=True, help_text='Maximum reduction percentage (0–100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='moleculeneutralization',
            name='reduction_percent_min',
            field=models.SmallIntegerField(blank=True, help_text='Minimum reduction percentage (0–100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='safetyscorerevision',
            name='new_health_index',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='safetyscorerevision',
            name='new_safety_score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='safetyscorerevision',
            name='old_health_index',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='safetyscorerevision',
            name='old_safety_score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='study',
            name='ai_health_impact',
            field=models.SmallIntegerField(blank=True, help_text='−5 to +5. AI-assessed impact on health perception.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='study',
            name='ai_safety_impact',
            field=models.SmallIntegerField(blank=True, help_text='−5 to +5. AI-assessed impact on safety perception.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('overall_safety_score__isnull', True), models.Q(('overall_safety_score__gte', 0), ('overall_safety_score__lte', 100)), _connector='OR'), name='food_overall_safety_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('health_index__isnull', True), models.Q(('health_index__gte', 0), ('health_index__lte', 100)), _connector='OR'), name='food_health_index_0_100'),
        ),
        migrations.AddConstraint(
            model_name='molecule',
            constraint=models.CheckConstraint(condition=models.Q(('harm_level__gte', 0), ('harm_level__lte', 5)), name='molecule_harm_level_0_5'),
        ),
        migrations.AddConstraint(
            model_name='moleculeneutralization',
            constraint=models.CheckConstraint(condition=models.Q(('reduction_percent_min__isnull', True), models.Q(('reduction_percent_min__gte', 0), ('reduction_percent_min__lte', 100)), _connector='OR'), name='neutralization_reduction_min_0_100'),
        ),
        migrations.AddConstraint(
            model_name='moleculeneutralization',
            constraint=models.CheckConstraint(condition=models.Q(('reduction_percent_max__isnull', True), models.Q(('reduction_percent_max__gte', 0), ('reduction_percent_max__lte', 100)), _connector='OR'), name='neutralization_reduction_max_0_100'),
        ),
        migrations.AddConstraint(
            model_name='safetyscorerevision',
            constraint=models.CheckConstraint(condition=models.Q(('old_safety_score__isnull', True), models.Q(('old_safety_score__gte', 0), ('old_safety_score__lte', 100)), _connector='OR'), name='revision_old_safety_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='safetyscorerevision',
            constraint=models.CheckConstraint(condition=models.Q(('new_safety_score__isnull', True), models.Q(('new_safety_score__gte', 0), ('new_safety_score__lte', 100)), _connector='OR'), name='revision_new_safety_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='safetyscorerevision',
            constraint=models.CheckConstraint(condition=models.Q(('old_health_index__isnull', True), models.Q(('old_health_index__gte', 0), ('old_health_index__lte', 100)), _connector='OR'), name='revision_old_health_index_0_100'),
        ),
        migrations.AddConstraint(
            model_name='safetyscorerevision',
            constraint=models.CheckConstraint(condition=models.Q(('new_health_index__isnull', True), models.Q(('new_health_index__gte', 0), ('new_health_index__lte', 100)), _connector='OR'), name='revision_new_health_index_0_100'),
        ),
        migrations.AddConstraint(
            model_name='study',
            constraint=models.CheckConstraint(condition=models.Q(('ai_safety_impact__isnull', True), models.Q(('ai_safety_impact__gte', -5), ('ai_safety_impact__lte', 5)), _connector='OR'), name='study_ai_safety_impact_neg5_5'),
        ),
        migrations.AddConstraint(
            model_name='study',
            constraint=models.CheckConstraint(condition=models.Q(('ai_health_impact__isnull', True), models.Q(('ai_health_impact__gte', -5), ('ai_health_impact__lte', 5)), _connector='OR'), name='study_ai_health_impact_neg5_5'),
        ),
    ]
