export function formatGuideText(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const text = value.trim();
  return text.length > 0 ? text : null;
}

export function formatGuideMetadata(generatedBy: unknown, version: unknown): string | null {
  if (typeof generatedBy !== "string") return null;
  const by = generatedBy.trim();
  if (!by) return null;
  if (typeof version !== "number" || !Number.isFinite(version)) return null;
  const normalizedVersion = Math.trunc(version);
  if (normalizedVersion < 1) return null;
  return `Generated by ${by} \u00b7 v${normalizedVersion}`;
}
