import { describe, expect, test } from "bun:test";

import { formatGuideMetadata, formatGuideText } from "./guideDisplay";

describe("AI guide display helpers", () => {
  test("formatGuideText keeps trimmed non-empty guide copy", () => {
    expect(formatGuideText("  Eat with fiber.  ")).toBe("Eat with fiber.");
  });

  test("formatGuideText hides missing and malformed guide copy", () => {
    expect(formatGuideText(null)).toBeNull();
    expect(formatGuideText("   ")).toBeNull();
    expect(formatGuideText({ text: "not displayable" })).toBeNull();
  });

  test("formatGuideMetadata normalizes valid generator and version values", () => {
    expect(formatGuideMetadata(" openrouter ", 2)).toBe("Generated by openrouter \u00b7 v2");
    expect(formatGuideMetadata("ai", 2.9)).toBe("Generated by ai \u00b7 v2");
  });

  test("formatGuideMetadata hides malformed metadata", () => {
    expect(formatGuideMetadata("", 1)).toBeNull();
    expect(formatGuideMetadata("ai", 0)).toBeNull();
    expect(formatGuideMetadata("ai", Number.NaN)).toBeNull();
    expect(formatGuideMetadata(123, 1)).toBeNull();
    expect(formatGuideMetadata("ai", "1")).toBeNull();
  });
});
